### PR TITLE
Remove couchdb fullnameOverride to use helm release name by default

### PR DESCRIPTION
**Pull request by evie-lau**
Seems like the fullnameOverride may have borked the umbrella chart deployment for 0.1.1 and 0.1.2 releases. 
This PR will update the 0.1.2 release only.

### CODE REVIEW

**Comment by jjvilleg** [comment]
Looks like the travis test needs to be updated since the fullnameoverride was removed.

**Comment by evie-lau** [comment]
note: previous commit 3060d34 requires repackaging helm chart

**Comment by evie-lau** [comment]
Travis script check for `populate` to finish is currently hardcoded to search for `cust-populate` on line 102. We should change this to use the release name env var.

**Review by jjvilleg — APPROVED** [review]
Great, go them passing.

**Pull request merged**
